name: YouTube Shorts Bot

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */3 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Repo indir
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Sistem paketleri
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Python kütüphaneleri
        run: |
          python -m pip install --upgrade pip
          pip install moviepy==1.0.3
          pip install imageio
          pip install imageio-ffmpeg
          pip install google-api-python-client
          pip install google-auth-oauthlib
          pip install requests

      - name: Botu çalıştır
        run: python auto_upload.py
